import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
      <body className="container">
        <main className="main">{children}</main>
        <footer className="footer">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
